version: "3"
services:
  lurch:
    image: node:10-alpine
    user: node
    env_file:
      - ./local.env
    volumes:
      - ../:/home/node
    working_dir: /home/node
    ports:
      - 3000:3000
    command: npm start
